
call main_tc








function main_tc
  print "Test case 1"
  call test_nonexisting_function_1

  print "Test case 2"
  call test_expect_mo_1
  call test_expect_so_1
  call test_expect_pe_1

  print "Test case 3"
  call test_script_syntax_1
  call test_script_syntax_2
  call test_script_syntax_3

  exit application
end












function test_nonexisting_function_1
  print "Calling a non-existing function"
  call this_function_does_not_exist
end


function test_expect_mo_1
  print "******************************************************"
  print "Expecting wrong number of MO"
  print "******************************************************"
  delete all mo
  add mo 1
  expect getnumberofmo 0
  delete all mo
end


function test_expect_so_1
  print "******************************************************"
  print "Expecting wrong number of SO"
  print "******************************************************"
  delete all so
  add so 1
  expect getnumberofso 0
  delete all so
end


function test_expect_pe_1
  print "******************************************************"
  print "Expecting wrong number of PE"
  print "******************************************************"
  delete all pe
  add pe 1
  expect getnumberofpe 0
  delete all pe
end


function test_script_syntax_1
  print "******************************************************"
  print "Unexpected end of function"
  print "******************************************************"
  var1 = 4
  if var1 == 4
  // Unexpected end of function
end


function test_script_syntax_2
  print "******************************************************"
  print "Unexpected endif"
  print "******************************************************"
  var1 = 4
  // Unexpected endif
  endif
end


function test_script_syntax_3
  print "******************************************************"
  print "Assignment operator in if construction"
  print "******************************************************"
  var1 = 1
  if var1 = 4
    var1 = 5
  endif
  // This error is not expected. Execution should have stopped after the first error.
  expect var1 0
end

















